spring:
  profiles: dev

gateway:
  port: 2025
  routes:
    - id: 1
      description: LOGIN
      topic: im_tx_user_topic
    - id: 2
      description: LOGOUT
      topic: im_tx_user_topic
    - id: 3
      description: PING
      topic: im_tx_api_topic
    - id: 4
      descirption: PONG
      topic: im_tx_api_topic