spring:
  profiles: dev

gateway:
  port: 2025
  maxConnect: 30000
  maxThreads: 8
  routes:
    - id: 1
      description: CONNECT
      topic: im_tx_user_topic
    - id: 2
      description: DISCONNECT
      topic: im_tx_user_topic
    - id: 3
      description: PING
      topic: im_tx_api_topic
    - id: 4
      descirption: PONG
      topic: im_tx_api_topic
    - id: 5
      description: PUSH_PRIVATE_MSG
      topic: im_tx_private_msg_topic
    - id: 6
      description: PUSH_GROUP_MSG
      topic: im_tx_group_msg_topic
